"""Alias de nombres de dispositivos."""

# Mapeo de nombres comunes que el LLM podría usar → pt_type
MODEL_ALIASES: dict[str, str] = {
    # Generic names
    "router":       "2911",
    "switch":       "2960-24TT",
    "pc":           "PC-PT",
    "computer":     "PC-PT",
    "server":       "Server-PT",
    "laptop":       "Laptop-PT",
    "tablet":       "TabletPC-PT",
    "smartphone":   "SMARTPHONE-PT",
    "phone":        "SMARTPHONE-PT",
    "printer":      "Printer-PT",
    "cloud":        "Cloud-PT",
    "wan":          "Cloud-PT",
    "ap":           "AccessPoint-PT",
    "wifi":         "AccessPoint-PT",
    "access_point": "AccessPoint-PT",
    "hub":          "Hub-PT",
    "firewall":     "5506-X",
    "asa":          "5506-X",
    "wlc":          "WLC-PT",
    "wireless_controller": "WLC-PT",
    "lap":          "LAP-PT",
    "lightweight_ap": "LAP-PT",
    "dsl":          "DSL-Modem-PT",
    "cable_modem":  "Cable-Modem-PT",
    "modem":        "DSL-Modem-PT",
    # Routers by model number
    "1841":         "1841",
    "1941":         "1941",
    "2811":         "2811",
    "2901":         "2901",
    "2911":         "2911",
    "4321":         "ISR4321",
    "isr4321":      "ISR4321",
    "4331":         "ISR4331",
    "isr4331":      "ISR4331",
    # Switches by model number
    "2950":         "2950-24",
    "2960":         "2960-24TT",
    "3560":         "3560-24PS",
    "3650":         "3650-24PS",
    # ASA firewalls
    "5505":         "5505",
    "5506":         "5506-X",
    "5506x":        "5506-X",
}
